spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: GB
    password: GB2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true